# Generated by Django 5.0.1 on 2024-01-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='')),
                ('text', models.TextField(max_length=500, verbose_name='')),
                ('button_text', models.CharField(max_length=255, verbose_name='')),
                ('button_link', models.URLField(max_length=255, verbose_name='')),
                ('image', models.ImageField(upload_to='header_images/', verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'Header Info',
            },
        ),
    ]
