# Generated by Django 5.0.1 on 2024-01-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_header_button_link_alter_header_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='navbar_images/', verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'Navbar Info',
            },
        ),
    ]
