# Generated by Django 5.0.1 on 2024-01-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_navbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_head', models.CharField(max_length=255, verbose_name='')),
                ('title', models.CharField(max_length=255, verbose_name='')),
                ('description', models.TextField(max_length=500, verbose_name='')),
                ('order', models.PositiveSmallIntegerField()),
                ('is_visible', models.BooleanField(default=True, verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ('order',),
            },
        ),
        migrations.DeleteModel(
            name='Navbar',
        ),
    ]
