# Generated by Django 5.0.1 on 2024-01-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_service_delete_navbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='title_head',
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Доступно/Недоступно'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
