# Generated by Django 5.0.1 on 2024-01-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_remove_service_title_head_alter_service_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='')),
                ('post', models.CharField(max_length=255, verbose_name='')),
                ('image', models.ImageField(upload_to='portfolio_images/', verbose_name='')),
                ('order', models.PositiveSmallIntegerField()),
                ('is_visible', models.BooleanField(default=True, verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ('order',),
            },
        ),
    ]
