# Generated by Django 5.0.1 on 2024-01-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_about_alter_portfolio_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='')),
                ('post', models.CharField(max_length=255, verbose_name='')),
                ('twitter', models.URLField(max_length=255, verbose_name='')),
                ('facebook', models.URLField(max_length=255, verbose_name='')),
                ('linkedin', models.URLField(max_length=255, verbose_name='')),
                ('image', models.ImageField(upload_to='team_images/', verbose_name='')),
                ('description', models.TextField(max_length=750, verbose_name='')),
                ('order', models.PositiveSmallIntegerField()),
                ('is_visible', models.BooleanField(default=True, verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'Team Items',
                'ordering': ('order',),
            },
        ),
    ]
