# Generated by Django 5.0.1 on 2024-01-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0008_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.URLField(max_length=255, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='team_images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Доступно/Недоступно'),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin',
            field=models.URLField(max_length=255, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='team',
            name='post',
            field=models.CharField(max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.URLField(max_length=255, verbose_name='Twitter'),
        ),
    ]
