# Generated by Django 5.0.1 on 2024-01-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0009_remove_team_description_alter_team_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('image', models.ImageField(upload_to='client_images/', verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField()),
                ('is_visible', models.BooleanField(default=True, verbose_name='Доступно/Недоступно')),
                ('link', models.URLField(max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name_plural': 'Client Items',
                'ordering': ('order',),
            },
        ),
    ]
