# Generated by Django 5.0 on 2024-01-17 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0011_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number should be in format: +380xxxxxxxxx', regex='^\\+?\\d{7,12}$')])),
                ('message', models.TextField(blank=True, max_length=500, verbose_name='')),
                ('is_precessed', models.BooleanField(default=False, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
