# Generated by Django 5.0 on 2024-01-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0013_alter_contactus_options_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title', models.CharField(max_length=100, verbose_name='')),
                ('portfolio_title', models.CharField(max_length=100, verbose_name='')),
                ('about_title', models.CharField(max_length=100, verbose_name='')),
                ('team_title', models.CharField(max_length=100, verbose_name='')),
                ('team_description', models.TextField(max_length=500, verbose_name='')),
                ('contact_title', models.CharField(max_length=100, verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'Main Site Items',
            },
        ),
    ]
