# Generated by Django 5.0 on 2024-01-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0015_alter_mainitems_about_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Project Name')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Project Title')),
                ('image', models.ImageField(upload_to='portfolio_modal_images/', verbose_name='Фото')),
                ('description', models.TextField(max_length=500, verbose_name='Project Description')),
                ('client', models.CharField(max_length=100, verbose_name='Client')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Доступно/Недоступно')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Portfolio Modals',
                'ordering': ('order',),
            },
        ),
    ]
